Features/1.0.8
dataiku/dss-plugin-sharepoint-online pull request #20
Opened 2021-03-17 15:44 UTC by alexbourret

2021-03-17 15:47 UTC, alexbourret commented
- Improved logging
- Adds form digest value to posts
- Adds retries on get & post following connection reset by peer, throttling events (429 errors)
- Adds session reset following 403 errors

2021-03-25 15:08 UTC, andreybavt requested changes
Generally looks good, I added a few comments.
However I'm a newbie because I never used Sharepoint.

2021-03-25 15:08 UTC, andreybavt commented on python-lib/robust_session.py
> +            if response.status_code == 403:
Out of curiosity, why does Microsoft reject our calls? Do they have a policy on how often their API can be called?

2021-03-25 17:23 UTC, alexbourret commented on python-lib/sharepoint_client.py
> +        headers = {
👍

2021-03-26 15:57 UTC, andreybavt commented on python-connectors/sharepoint-online_lists/connector.py
> +                column[SharePointConstants.TITLE_COLUMN],
ok, it was a cosmetic preference

2021-03-26 16:01 UTC, andreybavt approved these changes

2021-03-26 16:03 UTC, merged