Handling HTML error messages
dataiku/dss-plugin-sharepoint-online pull request #40
Opened 2022-07-13 10:02 UTC by alexbourret

Story details: https://app.shortcut.com/dataiku/story/94528

2022-08-30 14:43 UTC, liamlynch-data requested changes
There's a change to make as we discussed. Otherwise looks good (one other minor point below)

2022-08-30 14:43 UTC, liamlynch-data commented on python-lib/common.py
> +        time.sleep(seconds_before_retry)
Discussed - this case shouldn't return false, in fact, but should throw an exception which is caught higher up before the JSON parsing will fail and cause a crash.
(Sleeping is also not necessary)

2022-08-30 14:43 UTC, liamlynch-data commented on python-lib/common.py
> +        time.sleep(seconds_before_retry)
And we can test the exception is thrown in test_common.py

2022-09-01 07:34 UTC, alexbourret commented on python-lib/common.py
> +        time.sleep(seconds_before_retry)
After trying this approach, it appears that raising exception on non json pages results in creating a new set of issues. So I removed this part of the code in [eef49be](https://github.com/dataiku/dss-plugin-sharepoint-online/pull/40/commits/eef49bef27aa94c169b3ea82ed8cab38636ae52e)

2022-09-01 07:43 UTC, alexbourret commented on python-lib/common.py
> +            logger.warning("dumping content: {}".format(response.content))
👍  Done in [d7b6809](https://github.com/dataiku/dss-plugin-sharepoint-online/pull/40/commits/d7b680962b55b6f066c3a621a5fc13524d1e7ee8)

2022-09-01 09:28 UTC, alexbourret commented on tests/python/unit/test_common.py
> +        self.mock_response_http_200 = MockResponse(200, {"Content-Type": "application/json", "Retry-After": "1"})
👍  done in [c217142](https://github.com/dataiku/dss-plugin-sharepoint-online/pull/40/commits/c2171428e45bd9227517be826e23caa8b1e484a7)

2022-09-01 11:29 UTC, liamlynch-data commented on tests/python/unit/test_common.py
> +        self.mock_response_http_200 = MockResponse(200, {"Content-Type": "application/json", "Retry-After": "1"})
Great - thanks!

2022-09-01 11:30 UTC, liamlynch-data commented on python-lib/common.py
> +        time.sleep(seconds_before_retry)
Looks like the best soln, all good from my POV

2022-09-01 11:57 UTC, merged